research_task:
  description: >
    Conduzir uma pesquisa completa sobre o cliente e os concorrentes no contexto
    de {customer_domain}.
    Certifique-se de encontrar qualquer informação interessante e relevante, dado que
    o ano atual é 2024.
    Estamos trabalhando com eles no seguinte projeto: {project_description}.
  expected_output: >
    Um relatório completo sobre o cliente e seus clientes e concorrentes,
    incluindo seus dados demográficos, preferências, posicionamento no mercado e engajamento do público.

project_understanding_task:
  description: >
    Compreender os detalhes do projeto e o público-alvo para
    {project_description}.
    Revisar quaisquer materiais fornecidos e reunir informações adicionais conforme necessário.
  expected_output: >
    Um resumo detalhado do projeto e um perfil do público-alvo.

marketing_strategy_task:
  description: >
    Formular uma estratégia de marketing abrangente para o projeto
    {project_description} do cliente {customer_domain}.
    Use os insights da tarefa de pesquisa e da tarefa de compreensão do projeto
    para criar uma estratégia de alta qualidade.
  expected_output: >
    Um documento detalhado de estratégia de marketing que delineia os objetivos, público-alvo,
    mensagens-chave e táticas propostas. Certifique-se de incluir nome, táticas, canais e KPIs.

campaign_idea_task:
  description: >
    Desenvolver ideias criativas de campanhas de marketing para {project_description}.
    Certifique-se de que as ideias sejam inovadoras, envolventes e alinhadas com a estratégia geral de marketing.
  expected_output: >
    Uma lista de 5 ideias de campanhas, cada uma com uma breve descrição e impacto esperado.

copy_creation_task:
  description: >
    Criar textos de marketing baseados nas ideias de campanha aprovadas para {project_description}.
    Certifique-se de que os textos sejam atraentes, claros e direcionados ao público-alvo.
  expected_output: >
    Textos de marketing para cada ideia de campanha.
